//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmsnfManageMapping.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"OmsnfOrs.ZfPub.MsgUserdata.ZfSub.OmsnfQueryserver|OmsManageMapping.ZfPub.MsgMapping.ZfSub.OmsManageSystem|OmsManageMapping.ZfPub.MsgInitMapping.ZfSub.OmsManageSystem|OmsManageSystem.ZfPub.MsgRequest.ZfSub.OmsManageMapping|OmsManageSystem.ZfPub.MsgMapping.ZfSub.OmsManageMapping")]
        public string topic {
            get {
                return ((string)(this["topic"]));
            }
            set {
                this["topic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.168.2.10:2181")]
        public string ZooKeeperPath {
            get {
                return ((string)(this["ZooKeeperPath"]));
            }
            set {
                this["ZooKeeperPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/oms/dev/ver2.11/topics")]
        public string topicPath {
            get {
                return ((string)(this["topicPath"]));
            }
            set {
                this["topicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\e223377270\\\\Desktop\\\\subUserData")]
        public string folderPath {
            get {
                return ((string)(this["folderPath"]));
            }
            set {
                this["folderPath"] = value;
            }
        }
    }
}
